# SPDX-License-Identifier: Apache-2.0

name: Conftest

on:
  push:
    branches:
      - main
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.json"
      - "policy/**"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.json"
      - "**/policy/**"

jobs:
  conftest:
    name: Conftest Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run Conftest
        uses: sentenz/actions/conftest@latest
        with:
          policy-path: "./tests/policy"
