# SPDX-License-Identifier: Apache-2.0

name: Regal

on:
  push:
    branches:
      - main
    paths:
      - "**/*.rego"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rego"

permissions:
  contents: read

jobs:
  regal:
    name: Regal Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Regal
        uses: sentenz/actions/regal@203e2895cb7b6d09d5a822c04c86b7e8d2081d7e
        with:
          path: "./tests/policy"
          regal-version: "latest"
