# SPDX-License-Identifier: Apache-2.0

name: Renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run in dry-run mode"
        required: false
        default: "false"
        type: boolean
  schedule:
    # Run weekly on Sundays at 4:00 AM UTC
    - cron: "0 4 * * 0"

jobs:
  renovate:
    name: Renovate Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      checks: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run Renovate
        uses: sentenz/actions/renovate@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          autodiscover: "true"
          dry-run: ${{ inputs.dry-run || 'false' }}
          log-level: "info"
