# SPDX-License-Identifier: Apache-2.0
#
# Example: Semantic Release Workflow
#
# This workflow demonstrates how to use the semantic-release action
# for automated versioning and releases.

name: Semantic-Release

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha

jobs:
  semantic-release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    outputs:
      new-release-published: ${{ steps.release.outputs.new-release-published }}
      new-release-version: ${{ steps.release.outputs.new-release-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Semantic Release
        id: release
        uses: sentenz/actions/semantic-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: "false"

      - name: Release Summary
        if: steps.release.outputs.new-release-published == 'true'
        run: |
          echo "## 🎉 New Release Published!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ steps.release.outputs.new-release-version }}" >> $GITHUB_STEP_SUMMARY
