# SPDX-License-Identifier: Apache-2.0

name: Semgrep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Semgrep
        uses: sentenz/actions/semgrep@203e2895cb7b6d09d5a822c04c86b7e8d2081d7e
        with:
          config: "auto"
          metrics: "auto"
          no-secrets-validation: "true"
          sarif-output: "semgrep-results.sarif"

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          sarif_file: semgrep-results.sarif
        continue-on-error: true
