# SPDX-License-Identifier: Apache-2.0

name: Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  vulnerability-scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run Trivy vulnerability scan
        uses: sentenz/actions/trivy@latest
        with:
          scan-type: fs
          scan-target: .
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL

      - name: Upload results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
        continue-on-error: true

  sbom-generate:
    name: Generate SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Generate CycloneDX SBOM
        uses: sentenz/actions/trivy@latest
        with:
          scan-type: sbom-generate
          scan-target: .
          format: cyclonedx
          output: sbom.cdx.json

      - name: Generate SPDX SBOM
        uses: sentenz/actions/trivy@latest
        with:
          scan-type: sbom-generate
          scan-target: .
          format: spdx-json
          output: sbom.spdx.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: |
            sbom.cdx.json
            sbom.spdx.json

      - name: Publish SBOM to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sbom.cdx.json
            sbom.spdx.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sbom-scan:
    name: Scan SBOM
    runs-on: ubuntu-latest
    needs: sbom-generate
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Download SBOM artifacts
        uses: actions/download-artifact@v4
        with:
          name: sbom-files

      - name: Scan SBOM for vulnerabilities
        uses: sentenz/actions/trivy@latest
        with:
          scan-type: sbom
          scan-target: sbom.cdx.json
          format: table
          severity: HIGH,CRITICAL
        continue-on-error: true

  license-compliance:
    name: License Compliance
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run license compliance scan
        uses: sentenz/actions/trivy@latest
        with:
          scan-type: fs
          scan-target: .
          scanners: license
          format: table
          license-full: "true"
        continue-on-error: true

  iac-scan:
    name: IaC Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run IaC misconfiguration scan
        uses: sentenz/actions/trivy@latest
        with:
          scan-type: config
          scan-target: .
          format: sarif
          output: trivy-iac.sarif
          severity: HIGH,CRITICAL

      - name: Upload IaC results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-iac.sarif
        continue-on-error: true
