# SPDX-License-Identifier: Apache-2.0

name: VS Code Extension

on:
  release:
    types: [published]

jobs:
  vscode-extension:
    name: VS Code Extension Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"

      - name: VS Code Extension
        id: extension
        uses: sentenz/actions/vscode-extension@203e2895cb7b6d09d5a822c04c86b7e8d2081d7e
        with:
          marketplace-token: ${{ secrets.VSCE_PAT }}
          version: ${{ github.event.release.tag_name }}
          output-path: "artifacts/extension.vsix"
          skip-duplicate: "true"
