# SPDX-License-Identifier: Apache-2.0

name: VS Code Extension

on:
  release:
    types: [published]

jobs:
  vscode-extension:
    name: VS Code Extension Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"

      - name: VS Code Extension
        id: extension
        uses: sentenz/actions/vscode-extension@eeb59ec6f18d51aee1f04136bfedceaa02d346f9
        with:
          marketplace-token: ${{ secrets.VSCE_PAT }}
          version: ${{ github.event.release.tag_name }}
          output-path: "artifacts/extension.vsix"
          skip-duplicate: "true"
