# SPDX-License-Identifier: Apache-2.0

name: Regal Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.rego"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rego"

jobs:
  regal:
    name: Regal Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run Regal Test
        uses: ./regal
        with:
          path: "./tests/policy"
          output-format: "github"
          regal-version: "latest"
