# SPDX-License-Identifier: Apache-2.0

name: Regal Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.rego"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rego"

jobs:
  regal:
    name: Regal Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Regal Test
        uses: ./regal
        with:
          path: "./tests/policy"
          output-format: "github"
          regal-version: "latest"
