# SPDX-License-Identifier: Apache-2.0

name: Renovate Test

on:
  workflow_dispatch:
  schedule:
    # yamllint disable-line rule:quoted-strings
    - cron: "0 18 * * 6"

jobs:
  renovate:
    uses: ./.github/workflows/renovate.yml
    permissions:
      contents: read
    secrets:
      renovate-token: ${{ secrets.RENOVATE_TOKEN }}
