# SPDX-License-Identifier: Apache-2.0

name: Renovate Test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * 6

jobs:
  renovate:
    uses: ./.github/workflows/renovate.yml
    secrets:
      renovate-token: ${{ secrets.RENOVATE_TOKEN }}
