# SPDX-License-Identifier: Apache-2.0

name: Semgrep Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Semgrep Test
        uses: ./semgrep
        with:
          path: "."
          config: "p/default"
          metrics: "off"
          no-secrets-validation: "true"
        continue-on-error: true

      - name: Upload SARIF (if produced)
        if: always()
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
          sarif_file: semgrep-results.sarif
        continue-on-error: true
