# SPDX-License-Identifier: Apache-2.0

name: VS Code Extension Test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "vscode-extension/**"
      - ".github/workflows/vscode-extension-test.yml"
  pull_request:
    branches: [main]
    paths:
      - "vscode-extension/**"
      - ".github/workflows/vscode-extension-test.yml"

jobs:
  vscode-extension:
    name: VS Code Extension Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"

      - name: Run VS Code Extension
        uses: ./vscode-extension
        with:
          working-directory: "vscode-extension/test"
          output-path: "dist/test-extension-patch.vsix"
          version: "patch"
          no-dependencies: "true"
          publish: "false"
